### ISSUE TITLE
Sometimes "Build" is added between major and minor version number

### ISSUE THREAD

**Issue by Roald87** [Roald87/InfoSysCrawler#1]
Version number is not correctly detected if Build is added: 
- [`TwinCAT v3.1 Build 4022.30`](https://infosys.beckhoff.com/english.php?content=../content/1033/tcplclib_tc2_systemcx/10008435339.html&id=8006784332212369177)
- [`TwinCAT v3.1. >= 4022.31`](https://infosys.beckhoff.com/english.php?content=../content/1033/tcplclib_tc2_iofunctions/6811367563.html&id=3366609942436337282)

To 3.1's to check:
- Added: [`Tc2_System.F_GetTaskTime`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_system/3623060619.html?id=4232008823358802597)
- Added: [`Tc2_System.F_GetSystemTime`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_system/3622991755.html?id=6591934602709167291)
- Added: [`Tc2_SystemCX.F_CX8190_LED_WD`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_systemcx/10009196683.html?id=7849602325543438949)
- Added: [`Tc2_SystemCX.F_CX8190_LED_ERR`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_systemcx/10008435339.html?id=8006784332212369177)
- Added: [`Tc2_SystemCX.F_CX8180_LED_WD`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_systemcx/10008209163.html?id=7049132632932433567)
- Added: [`Tc2_SystemCX.F_CX8180_LED_ERR`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_systemcx/10008172299.html?id=3151541491560267304)
- Added: [`Tc2_SystemCX.F_CX81xx_ADDRESS`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_systemcx/10007958667.html?id=8625799869606053059)
- Added: [`Tc2_SystemCX.F_CXNaviSwitchUSB`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_systemcx/2220172939.html?id=3198719063883044768)
- Added: [`Tc2_SystemCX.F_CXSubTimeStamp`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_systemcx/185874699.html?id=6487027106657902772)
- Added: [`Tc2_SystemCX.FB_CXGetTextDisplayUSB`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_systemcx/2089318411.html?id=6193447741261586233)
- Added: [`Tc2_SystemCX.FB_CXSetTextDisplayUSB`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_systemcx/2089254539.html?id=2081830548769362910)
- Added: [`Tc2_SystemCX.FB_CXProfiler`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_systemcx/185861003.html?id=5508204120391433760)
- Added: [`Tc2_SystemCX.FB_CxGetDeviceIdentificationEx`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_systemcx/2239506699.html?id=4566415975073608622)
- Added: [`Tc2_SystemCX.FB_CxGetDeviceIdentification`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_systemcx/185859467.html?id=5567874876158473916)
- Added: [`Tc2_SUPS.FB_S_UPS_BAPI`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_sups/3716524299.html?id=7162402166301276776)
- Added: [`Tc2_SUPS.FB_S_UPS_CX9020_U900`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_sups/2250162827.html?id=5342180273230816921)
- Added: [`Tc2_SUPS.FB_S_UPS_CX51x0`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_sups/2250113931.html?id=5627610611515898967)
- Added: [`Tc2_SUPS.FB_S_UPS`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_sups/30498571.html?id=1599096140892917218)
- Added: [`Tc2_SUPS.FB_S_UPS_CB3011`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_sups/2220095883.html?id=3239293293187063130)
- Added: [`Tc2_MBus.FB_MBUS_EMH_MIZ`](https://infosys.beckhoff.com/../content/1033/tcplclib_tc2_mbus/174672267.html?id=3025965226451109759)

**Comment by rruiter87** [comment]
also https://github.com/Roald87/TwinCatChangelog/pull/63
